site_name: East Greenville Beer Bash
dev_addr: localhost:8000
theme:
  name: null
  custom_dir: custom_cinder/
  disable_nav_search: true
extra_css:
- css/extra.css
- https://cdnjs.cloudflare.com/ajax/libs/fancybox/1.3.4/jquery.fancybox-1.3.4.css
strict: true
markdown_extensions:
  - markdown_include.include
  - tables
use_directory_urls: false
nav:
  - index.md
plugins:
  - bootstrap-tables

